import org.apache.spark._
import org.apache.log4j._
import org.apache.spark.sql._
import org.apache.spark.sql.functions.udf
import org.apache.spark.sql.types.{IntegerType, StringType, StructField, StructType}

object FortuneCompanies{
  def main(args: Array[String]): Unit = {

    //To Print only Error Logs
    Logger.getLogger("org").setLevel(Level.ERROR)

      //Creating Spark Session
    val spark = SparkSession.builder().appName("FortuneCompanies").master("local[*]").getOrCreate()

    //Importing Spark Implicits
    import spark.implicits._

    var schema = StructType(Array(StructField("Year",IntegerType,nullable = true),
                StructField("Rank",IntegerType,nullable = true),
                StructField("InverseRank",IntegerType,nullable = true),
                StructField("Company",StringType,nullable = true),
                StructField("Revenue",IntegerType,nullable = true),
                StructField("Profit",IntegerType,nullable = true)
              ))

    //Reading the csv file
    val company = spark.read.format("csv").option("header","true").option("delimiter","\t").schema(schema).load("dataset/Fortune500Companies.txt")

    //Displaying the first 5 rows
    company.show(5)

    company.na.drop()

    company.printSchema()
    println("Data types are " + company.dtypes)

    //val toInt    = udf[Int, String]( _.toInt)
    //val company_df = company.withColumn("Profit",toInt(company("Profit")))

    //company_df.printSchema()
    //company_df.na.fill(0)

    //Displaying total Entries
    println("The Total number of Entries are "+ company.count())

    //Creating a temporary view to apply SQL queries
    company.createOrReplaceTempView("company")

    //Displaying 1st 5 data of a particular company
    spark.sql("select * from company where Company='General_Motors'").collect().take(5).foreach(println)

    //Displaying the range of Years
    spark.sql("select min(Year),max(Year) from company").show()

    //Displaying min and max profit of each company
    spark.sql("select Company , min(Profit),max(Profit) from company group by Company").show(10)


    //Displaying the Max Profit and min Profit from all the companies
    spark.sql("select min(Profit), max(Profit) from company").show(5)

    //Displaying all the Companies
    spark.sql("select distinct(Company) from company").show()


    //Displaying the total profit generated by all company
    spark.sql("select Company , sum(Profit) from company group by Company order by sum(Profit) desc").show(5)

    //Since Company "Exxon_Mobil" has the highest sum of profits , Lets Consider it for further analysis
    company.filter($"Company"==="Exxon_Mobil").createOrReplaceTempView("exxon")

    //Displaying first 5 rows of exxon company
    spark.sql("select * from exxon").show(5)

    //Average Profit of exxon company
    spark.sql("select avg(Profit) from exxon").show()

    //Difference between averages of best Profit Company(Exxon) and 2nd Best Company(General_Electric)
    spark.sql("select (select avg(Profit)  from exxon) - (select avg(Profit) from company where Company = 'General_Electric') as Difference  ").show()

    //Displaying the Top 10 Country with Highest Profit
    spark.sql("select Company , Profit from company order by Profit desc limit 10").show()

  }
}




